config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:create, :destroy]
  get '/sign-up', to: 'users#new', as: :sign_up

  namespace :admin do
    root 'products#index'
    resources :products do
      member do
        patch :setting_cover, :publish_operation
      end
    end
    resources :product_pictures
    resources :messages, except: [:show, :new, :create] 
    resources :users do
      delete :destroy_user_picture, on: :member
    end
    resources :product_categories
    resources :evaluates
  end

  %w( 404 422 500 ).each do |code|
    get code, to: "errors#show", code: code
  end

  resources :products, only: [:index, :show] do

    resources :messages, only: [:index, :create, :destroy] do
      collection do
        post :create_evaluate_message
      end
    end
    resources :evaluates
    resource :collectionship, only: [:create, :destroy]
    
  end
  resource :likeship, only: [:create, :destroy]
  
  resources :users, only: [:index, :show, :create] do
    member do
      get :all_evaluates
    end
  end

  resource :account, only: [:edit, :update] do
    collection do
      get :change_password
      patch :update_password, :setting_cover
    end
    resources :user_pictures, only: [:index, :show, :create, :destroy]
  end

  resources :notifications, only: [:index, :destroy]

  root 'products#index'
end

app/models/evaluate.rb
class Evaluate < ActiveRecord::Base

  belongs_to :product, counter_cache: true
  belongs_to :user
  has_many :messages, as: :messageable
  has_many :likeships, as: :likeable, foreign_key: "likeable_id", dependent: :destroy
  has_many :likers, through: :likeships, source: :user

  validates :title, :details, :product_id, :user_id, presence: true

  def last_page_with_per_page per_page
    page = (self.messages_count.to_f / per_page).ceil
    page > 1 ? page : nil
  end

  def self.search this_params
    evaluate = Evaluate.all
    evaluate = evaluate.where("title LIKE ?", "%#{this_params[:title]}%") if this_params[:title].present?
    evaluate = evaluate.joins(:product).where("products.name LIKE ?", "%#{this_params[:product]}%") if this_params[:product].present?
    evaluate = evaluate.joins(:user).where("users.name LIKE ?", "%#{this_params[:user]}%") if this_params[:user].present?
    evaluate.paginate(page: this_params[:page])
  end

end

app/controllers/admin/evaluates_controller.rb
class Admin::EvaluatesController < Admin::BaseController
  before_action :find_evaluate, only: [:show, :edit, :update, :destroy, :create_message, :destroy_message]
  
  def index
    @evaluates = Evaluate.search(params)
  end

  def show
  end

  def edit
  end
 
  def update
    if @evaluate.update(evaluate_params)
      flash[:success] = '更新成功！'
      redirect_to admin_evaluates_path
    else
      flash.now[:danger] = '更新失败，请重新更新！'
      render 'edit'
    end
  end

  def new
    @evaluate = Evaluate.new
  end

  def create
    @evaluate = Evaluate.new(evaluate_params)
    @evaluate.user_id = current_user.id
    if @evaluate.save
      flash[:success] = '创建成功！'
      redirect_to admin_evaluates_path
    else
      flash.now[:danger] = '创建失败，请重新创建！'
      render 'new'
    end
  end
 
  def destroy
    @evaluate.destroy
    @evaluates = Evaluate.search(params)
    flash[:success] = '删除成功！'
    if @evaluates.blank?
      redirect_to admin_evaluates_path
    else
      redirect_to :back
    end
  end

  private
    
    def find_evaluate
      @evaluate = Evaluate.find(params[:id])
    end

    def evaluate_params
      params.require(:evaluate).permit(:title, :details, :product_id)
    end
end

app/controllers/evaluates_controller.rb
class EvaluatesController < ApplicationController
  load_and_authorize_resource only: [:new, :edit, :create, :update, :destroy]
  before_action :find_product
  before_action :find_evaluate, only: [:show, :edit, :update, :destroy]
  
  def index
    @evaluates = @product.evaluates.order(id: :desc)
  end

  def show
    @per_page = Message.per_page
    params[:page] = @evaluate.last_page_with_per_page(@per_page) if params[:page].blank?
    @message = @evaluate.messages.build
    @messages = @evaluate.messages.paginate(page: params[:page], per_page: @per_page)
    @likeable = Likeship.likeable(@evaluate)
  end

  def new
    @evaluate = @product.evaluates.build
  end

  def create
    @evaluate = @product.evaluates.build(evaluate_params.merge(user: current_user))
    if @evaluate.save
      flash[:success] = '评测创建成功！'
      redirect_to product_evaluate_path(@product, @evaluate)
    else
      flash.now[:danger] = '创建失败，请重新创建！'
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:product_id])
  end

  def update
    if @evaluate.update(evaluate_params)
      flash[:success] = '评测编辑成功！'
      redirect_to product_evaluate_path(@product, @evaluate)
    else
      flash.now[:danger] = '编辑失败，请重新创建！'
      render 'edit'
    end
  end

  def destroy
    @evaluate.destroy
    flash[:success] = '删除成功！'
    redirect_to :back 
  end

  private
    def find_evaluate
      @evaluate = @product.evaluates.find(params[:id])
    end

    def find_product
      @product = Product.find(params[:product_id])
    end

    def evaluate_params
      params.require(:evaluate).permit(:title, :details)
    end

end

app/helpers/admin/evaluates_helper.rb
module Admin::EvaluatesHelper
end

app/helpers/evaluates_helper.rb
module EvaluatesHelper
end

app/views/admin/evaluates/_form.html.erb
<%= form_for(@evaluate, url: (@evaluate.new_record? ? admin_evaluates_path : admin_evaluate_path(@evaluate)), html: { class: "form-horizontal" }) do |f| %>
  <%= render "shared/error_messages", object: @evaluate %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <% if @evaluate.new_record? %>
    <div class="form-group">
      <%= f.label :product_id, class: "col-sm-1 control-label" %>
      <div class="col-sm-11">
        <%= f.select :product_id, options_from_collection_for_select(Product.all, :id, :name), {}, class: "form-control" %>
      </div>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.label :product_id, class: "col-sm-1 control-label" %>
      <div class="col-sm-11">
        <p class="form-control-static">
          <%= @evaluate.product.try(:name) %>
        </p>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :user_id, class: "col-sm-1 control-label" %>
      <div class="col-sm-11">
        <p class="form-control-static">
          <%= @evaluate.user.try(:name) %>
        </p>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :details, class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.text_area :details, class: "form-control rich_text_format" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-11">
        <%= f.submit "确认提交", class: 'btn btn-primary', data: { disable_with: "正在提交..." } %>
    </div>
  </div>
<% end %>

app/views/admin/evaluates/_search_form.html.erb
<%= form_tag admin_evaluates_path, class: "form-inline", method: "get" do %>
  <div class="form-group">
    <%= text_field_tag :title, params[:title], placeholder: "标题", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= text_field_tag :product, params[:product], placeholder: "产品", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= text_field_tag :user, params[:user], placeholder: "用户", class: "form-control" %>
  </div>
  <%= submit_tag "搜索", class: "btn btn-primary "%>
  <%= link_to "返回", admin_evaluates_path, class: "btn btn-default" %>
<% end %>

app/views/admin/evaluates/index.html.erb
<div class="page-header">
  <h2>
    产品评测管理
    <small class="pull-right">
      <%= link_to "创建新评测", new_admin_evaluate_path, class: "btn btn-primary" %>
    </small>
  </h2>
</div>

<%= render "search_form" %>
<hr>

<%= will_paginate @evaluates, renderer: BootstrapPagination::Rails %>
<table class="table table_hover">
  <thead>
    <tr>
      <th>标题</th>
      <th>评测产品</th>
      <th>评测用户</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluates.each do |evaluate| %>
      <tr>
        <td><%= link_to evaluate.title, admin_evaluate_path(evaluate) %></td>
        <td><%= evaluate.product.try(:name) %></td>
        <td><%= evaluate.user.try(:name) %></td>
        <td>
          <%= link_to "编辑", edit_admin_evaluate_path(evaluate), class: "btn btn-primary btn-sm" %>
          <%= link_to "删除", admin_evaluate_path(evaluate, page: params[:page]), class: "btn btn-danger btn-sm", data: { confirm: "请问您确定要删除吗？" }, method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @evaluates, renderer: BootstrapPagination::Rails %>

app/views/admin/evaluates/show.html.erb
<div class="page-header">
  <h2>
    <%= @evaluate.title %>
  </h2>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="media">
      <div class="media-body">
        <h5 class="media-heading">
          用户：<%= link_to @evaluate.user.try(:name), user_path(@evaluate.user) %>
        </h5>
        <div>
          <small>
            编辑：
            <%= link_to fa_icon("pencil-square-o"), edit_admin_evaluate_path(@evaluate) %>
          </small>           
        </div> 
        <div>
          <small>
            <%= fa_icon("clock-o") %>
            创建时间：<%= @evaluate.created_at.strftime "%Y-%m-%d %H:%M:%S" %> ／ 
            <%= fa_icon("leaf") %> 
            产品：<%= @evaluate.product.try(:name) %>             
          </small>
        </div>
      </div>
    </div>
    <hr>
    <div>
      <%= sanitize(@evaluate.details) %>
    </div>
  </div>
</div>