config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:create, :destroy]
  get '/sign-up', to: 'users#new', as: :sign_up

  namespace :admin do
    root 'products#index'
    resources :products do
      member do
        patch :setting_cover, :publish_operation
      end
    end
    resources :product_pictures
    resources :messages, except: [:show, :new, :create] 
    resources :users do
      delete :destroy_user_picture, on: :member
    end
    resources :product_categories
    resources :evaluates
  end

  %w( 404 422 500 ).each do |code|
    get code, to: "errors#show", code: code
  end

  resources :products, only: [:index, :show] do

    resources :messages, only: [:index, :create, :destroy] do
      collection do
        post :create_evaluate_message
      end
    end
    resources :evaluates
    resource :collectionship, only: [:create, :destroy]
    
  end
  resource :likeship, only: [:create, :destroy]
  
  resources :users, only: [:index, :show, :create] do
    member do
      get :all_evaluates
    end
  end

  resource :account, only: [:edit, :update] do
    collection do
      get :change_password
      patch :update_password, :setting_cover
    end
    resources :user_pictures, only: [:index, :show, :create, :destroy]
  end

  resources :notifications, only: [:index, :destroy]

  root 'products#index'
end

app/views/layouts/shared/_application_footer.html.erb
<div>
  <p class="copyright pull-right">
    <span>
      Copyright 2014 © 
      <%= link_to "Giggle", "https://github.com/minnowlab/giggle", target: "_blank" %>
    </span> 
  </p>
</div>

app/views/layouts/shared/_flash_notice.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/shared/_go_top.html.erb
<a class="go_top" href="#">
  <%= fa_icon "chevron-up" %>
</a>

app/views/layouts/shared/_sign_in_modal.html.erb
<div class="modal" id="sign_in_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">请登录</h4>
      </div>
      <%= form_tag session_path, class: "form-horizontal", remote: true do %>
        <div class="modal-body">
          <div id="sign_in_alert" class="hidden alert alert-danger"></div>
          <div class="form-group">
            <label class="control-label col-sm-3">邮箱</label>
            <div class="col-sm-7">
              <%= text_field_tag :email, "", class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-3">密码</label>
            <div class="col-sm-7">
              <%= password_field_tag :password, "", class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
              <div class="checkbox">
                <label>
                  <%= check_box_tag :remember_me, nil, false %>
                  记得我？
                </label>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= button_tag class: "btn btn-primary", type: :submit, data: { disable_with: "正在提交..." } do %>
            <i class="fa fa-sign-in"></i> 
            登录
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/shared/_user_them.html.erb
<div id="user_menu" class="list-group container_box">
  <%= link_to "修改用户信息", edit_account_path, class: "list-group-item" %>
  <%= link_to "修改密码", change_password_account_path, class: "list-group-item" %>
  <%= link_to "头像管理", account_user_pictures_path, class: "list-group-item" %>
</div>