config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:create, :destroy]
  get '/sign-up', to: 'users#new', as: :sign_up

  namespace :admin do
    root 'products#index'
    resources :products do
      member do
        patch :setting_cover, :publish_operation
      end
    end
    resources :product_pictures
    resources :messages, except: [:show, :new, :create] 
    resources :users do
      delete :destroy_user_picture, on: :member
    end
    resources :product_categories
    resources :evaluates
  end

  %w( 404 422 500 ).each do |code|
    get code, to: "errors#show", code: code
  end

  resources :products, only: [:index, :show] do

    resources :messages, only: [:index, :create, :destroy] do
      collection do
        post :create_evaluate_message
      end
    end
    resources :evaluates
    resource :collectionship, only: [:create, :destroy]
    
  end
  resource :likeship, only: [:create, :destroy]
  
  resources :users, only: [:index, :show, :create] do
    member do
      get :all_evaluates
    end
  end

  resource :account, only: [:edit, :update] do
    collection do
      get :change_password
      patch :update_password, :setting_cover
    end
    resources :user_pictures, only: [:index, :show, :create, :destroy]
  end

  resources :notifications, only: [:index, :destroy]

  root 'products#index'
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :message

  scope :user_notification, ->(user) { where(user: user) }
  scope :unread_scope, -> { where(read: false) }
  scope :read_scope, -> { where(read: true) }

  def self.find_my_notifications current_user
    notes = self.user_notification(current_user).order("id desc")
    unread = notes.unread_scope
    read = notes.read_scope
    notification = []
    notification += unread + read
    unread.update_all(read: true)
    notification
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = Notification.find_my_notifications current_user
  end

  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy
    flash[:success] = "删除成功！"
    redirect_to :back
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/notification/_evaluate.html.erb
<li class="row">
  <% if message.nil? %>
    <div class="col-md-11">
      该资源已删除！
    </div>
  <% else %>
    <div class="col-md-1">
      <%= link_to user_picture_cover(message.user.cover.try(:picture_url, :cover), "cover"), user_path(message.user) %>
    </div>
    <div class="col-md-10 notification_info">
      <h5>
        <%= link_to message.user.name, message.user %>
        <% if message.evaluate_author? notification %>
          回复了我发布的评测
          <%= link_to message.messageable_name, product_evaluate_path(message.messageable.product, message.messageable) %>
        <% else %>
          在对评测 
          <%= link_to message.messageable_name, product_evaluate_path(message.messageable.product, message.messageable) %>
          的回复中提到了我 
        <% end %>
        <small>
          <%= time_ago_in_words(notification.created_at) %>前 
        </small>
        <span class="label label-danger unread_notic">新</span>
      </h5>
      <div>
        <%= sanitize(message.content) %>
      </div>
    </div>
  <% end %>
  <div class="col-md-1">
    <%= link_to "删除", notification_path(notification), data: { confirm: "请问您确定要删除吗？" }, method: :delete, class: "btn btn-xs btn-danger" %>
  </div>
</li>

app/views/notifications/notification/_product.html.erb
<li class="row">
  <% if message.nil? %>
    <div class="col-md-11">
      该资源已删除！
    </div>
  <% else %>
    <div class="col-md-1">
      <%= link_to user_picture_cover(message.user.cover.try(:picture_url, :cover), "cover"), user_path(message.user) %>
    </div>
    <div class="col-md-10 notification_info">
      <h5>
        <%= link_to message.user.name, message.user %> 
        在对产品 
        <%= link_to message.messageable_name, product_path(message.messageable) %> 
        的回复中提到了我
        <small>
          <%= time_ago_in_words(notification.created_at) %>前 
        </small>
        <span class="label label-danger unread_notic">新</span>
      </h5>
      <div>
        <%= sanitize(message.content) %>
      </div>
    </div>
  <% end %>
  <div class="col-md-1">
    <%= link_to "删除", notification_path(notification), data: { confirm: "请问您确定要删除吗？" }, method: :delete, class: "btn btn-xs btn-danger" %>
  </div>
</li>