config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:create, :destroy]
  get '/sign-up', to: 'users#new', as: :sign_up

  namespace :admin do
    root 'products#index'
    resources :products do
      member do
        patch :setting_cover, :publish_operation
      end
    end
    resources :product_pictures
    resources :messages, except: [:show, :new, :create] 
    resources :users do
      delete :destroy_user_picture, on: :member
    end
    resources :product_categories
    resources :evaluates
  end

  %w( 404 422 500 ).each do |code|
    get code, to: "errors#show", code: code
  end

  resources :products, only: [:index, :show] do

    resources :messages, only: [:index, :create, :destroy] do
      collection do
        post :create_evaluate_message
      end
    end
    resources :evaluates
    resource :collectionship, only: [:create, :destroy]
    
  end
  resource :likeship, only: [:create, :destroy]
  
  resources :users, only: [:index, :show, :create] do
    member do
      get :all_evaluates
    end
  end

  resource :account, only: [:edit, :update] do
    collection do
      get :change_password
      patch :update_password, :setting_cover
    end
    resources :user_pictures, only: [:index, :show, :create, :destroy]
  end

  resources :notifications, only: [:index, :destroy]

  root 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  scope :published, -> { where("published_at IS NOT null") }

  has_many :messages, as: :messageable
  has_many :evaluates
  has_many :product_pictures
  has_many :collectionships, foreign_key: "product_id", dependent: :destroy
  has_many :collectors, through: :collectionships, source: :user
  has_many :likeships, as: :likeable, foreign_key: "likeable_id", dependent: :destroy
  has_many :likers, through: :likeships, source: :user
  belongs_to :product_category
  belongs_to :cover, class_name: "ProductPicture", foreign_key: "cover_id"

  validates :name, :product_category_id, presence: true

  def last_page_with_per_page per_page
    page = (self.messages_count.to_f / per_page).ceil
    page > 1 ? page : nil
  end

  def self.search this_params
    product = self.all
    product = product.where("name LIKE ? ", "%#{this_params[:name]}%") if this_params[:name].present?
    product = product.where("price < ?", this_params[:max_price]) if this_params[:max_price].present?
    product = product.where("price > ?", this_params[:min_price]) if this_params[:min_price].present?
    product = product.where(product_category_id: this_params[:product_category_id]) if this_params[:product_category_id].present?
    product.paginate(page: this_params[:page])
  end

  def self.classify_published this_params
    product = self.published
    product = product.where(product_category_id: this_params[:category]) if this_params[:category].present?
    product.paginate(page: this_params[:page], per_page: 6)
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :find_product, except: [:index, :new, :create]

  def index
    @products = Product.search(params)
  end

  def show
    @product_picture = ProductPicture.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = '创建成功！'
      redirect_to admin_product_path(@product)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:success] = '更新成功！'
      redirect_to admin_products_path
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    @products = Product.search(params)
    flash[:success] = '删除成功！'
    if @products.blank?
      redirect_to admin_products_path
    else
      redirect_to :back
    end
  end

  def setting_cover
    @product_picture = @product.product_pictures.where(id: params[:cover_id]).first
    @product.update(cover: @product_picture)
    flash[:success] = '设置成功成功！'
    redirect_to :back
  end

  def publish_operation
    publish_setting = @product.published_at.nil? ? Time.now : nil
    if @product.update(published_at: publish_setting)
      flash[:success] = '设置成功！'
      redirect_to admin_product_path(@product)
    else
      flash[:danger] = '设置失败，请重新设置！'
      redirect_to :back
    end
  end

  private
  
    def find_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :details, :buy_link, :price, :product_category_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :find_product, only: :show

  def index
    @products = Product.order(sort_column + " " + sort_direction).classify_published(params)
    @product_categories = ProductCategory.all
  end

  def show
    @evaluates = @product.evaluates.order(id: :desc).limit(3)
    @message = @product.messages.build
    @per_page = Message.per_page
    params[:page] = @product.last_page_with_per_page(@per_page) if params[:page].blank?
    @messages = @product.messages.paginate(page: params[:page], per_page: @per_page)
    @likeable = Likeship.likeable(@product)  
  end

  private

    def find_product
      @product = Product.find(params[:id])
    end

    def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_collection_tag product
    return fa_icon("bookmark") if current_user.blank?
    class_name = "icon_mark_select"
    link_title = "收藏"
    link_path_method = "post"
    if current_user and current_user.collectionship_product_ids.include?(product.id)
      class_name = "icon_mark_selected"
      link_title = "取消收藏"
      link_path_method = "delete"
    end
    link_to fa_icon("bookmark"), product_collectionship_path(product), class: class_name, "data-toggle"=>"tooltip", title: link_title, method: link_path_method, remote: true
  end  
end

app/views/admin/products/_add_product_picture_modal.html.erb
<div class="modal fade" id="add_product_picture_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">添加产品图片</h4>
      </div>
      <%= form_for(@product_picture, url: admin_product_pictures_path, html: {multipart: true}) do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :picture %>
            <%= f.file_field :picture %>
            <%= f.hidden_field :picture_cache %>
            <%= f.hidden_field :product_id, value: @product.id %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit "提交", class: 'btn btn-primary', data: { disable_with: "正在提交..." } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/products/_form.html.erb
<%= form_for(@product, url: (@product.new_record? ? admin_products_path : admin_product_path(@product)), html: { class: "form-horizontal" }) do |f| %>
  <%= render "shared/error_messages", object: @product %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.text_field :price, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :buy_link, class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.text_field :buy_link, class: "form-control" %>
      <p class="help-block">http://或者https://开头</p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :product_category_id, class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.select :product_category_id, options_from_collection_for_select(ProductCategory.all, :id, :name), {}, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :details, class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.text_area :details, class: "form-control rich_text_format" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-11">
        <%= f.submit "确认提交", class: 'btn btn-primary', data: { disable_with: "正在提交..." } %>
    </div>
  </div>
<% end %>

app/views/admin/products/_search_form.html.erb
<%= form_tag admin_products_path, method: "get", class: "form-inline" do %>
  <div class="form-group">
    <%= text_field_tag :name, params[:name], placeholder: "产品名称", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= text_field_tag :min_price, params[:min_price], placeholder: "最低价", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= text_field_tag :max_price, params[:max_price], placeholder: "最高价", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= select_tag :product_category_id, options_from_collection_for_select(ProductCategory.all, :id, :name, params[:product_category_id]), include_blank: true, class: "form-control" %>
  </div>
  <%= submit_tag "搜索", class: "btn btn-primary "%>
  <%= link_to "返回", admin_products_path, class: "btn btn-default" %>
<% end %>

app/views/admin/products/index.html.erb
<div class="page-header">
  <h2>
    产品管理
    <small class="pull-right"><%= link_to "创建新产品", new_admin_product_path, class: "btn btn-primary" %></small>
  </h2>
</div>

<%= render "search_form" %>
<hr>

<%= will_paginate @products, renderer: BootstrapPagination::Rails %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>名称</th>
      <th>描述</th>
      <th>价格</th>
      <th>产品类</th>
      <th>发布时间</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, admin_product_path(product) %></td>
        <td><%= product.description.truncate(10) %></td>
        <td><%= product.price %></td>
        <td><%= product.product_category.try(:name) %></td>
        <th><%= product.published_at.try(:strftime, "%Y-%m-%d %H:%M:%S") %></th>
        <td>
          <%= link_to "编辑", edit_admin_product_path(product), class: "btn btn-primary btn-sm" %>
          <%= link_to "删除", admin_product_path(product, page: params[:page]), class: "btn btn-danger btn-sm", data: { confirm: "请问您确定要删除吗？" }, method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @products, renderer: BootstrapPagination::Rails %>

app/views/admin/products/show.html.erb
<%= render "add_product_picture_modal" %>

<div class="row">
  <div class="col-md-3">
    <p class="lead">产品管理</p>
    <div class="list-group">
      <%= link_to "添加图片", "#add_product_picture_modal", class: "list-group-item",  "data-toggle" => "modal" %>
      <%= link_to_if @product.published_at.nil?, "产品发布", publish_operation_admin_product_path(@product), class: "list-group-item", method: :patch do %>
        <%= link_to "取消产品发布", publish_operation_admin_product_path(@product), class: "list-group-item", method: :patch %>
      <% end %>
    </div>
  </div>

  <div class="col-md-9">
    <div class="row">
      <div class="col-md-12">
        <div class="thumbnail">
          <div class="caption-full">
            <h4 class="pull-right">
              RMB <%= @product.price %>
            </h4>
            <h4>
              <i class="fa fa-glass"></i>
              <%= @product.name %>
            </h4>
            <p>
              发布时间：
              <%= @product.published_at.try(:strftime, "%Y-%m-%d %H:%M:%S") %> ／ 
              创建时间：
              <%= @product.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
            </p>
            <p>
              购买链接：
              <%= link_to_if @product.buy_link.present?, "点击查看", @product.buy_link, class: "btn btn-primary btn-xs", target: "_blank" do %>
                <%= link_to "暂不提供购买", "#", class: "btn btn-default btn-xs disabled" %>
              <% end %>
            </p>
            <p>
              <i class="fa fa-info-circle"></i>
              <%= @product.description %>
            </p>
            <hr>
            <p>
              <%= sanitize(@product.details) %>
            </p>
          </div>    
        </div>
      </div>
    </div>

    <div class="row">
      <hr>
      <% @product.product_pictures.each do |product_picture| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="thumbnail">
            <div class="product_picture">
              <%= image_tag product_picture.picture_url(:small) %>
            </div>
            <div class="caption">
              <%= link_to_if @product.cover == product_picture, "已设为封面", "#", class: "btn btn-info btn-xs disabled" do %>
                <%= link_to "设置为封面", setting_cover_admin_product_path(cover_id: product_picture.id), class: "btn btn-info btn-xs", method: :patch %>
              <% end %>
              <%= link_to "删除", admin_product_picture_path(product_picture), class: "btn btn-danger btn-xs", data: { confirm: "请问您确定要删除吗？" }, method: :delete %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>